app = "bitcoin-0-2-1t4c3g"
primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8333

  [[services.ports]]
    port = 8333

  [services.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

[deploy]
  strategy = "immediate"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
